version: '3.9'
services:
  db:
    volumes:
      - ./db-data:/var/lib/postgresql/data
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080